# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_CRS02bLab_session_18.*
  - observation_CRS02bLab_session_19.*
  exclude_datasets:
  - observation_CRS02bLab_session_19.* #
  - observation_CRS07Lab_session_15.*
  - observation_CRS07Lab_session_16.*
  # There are at least 4 test sessions for CRS07 and 8 for CRS02bLab
train:
  autoscale_batch_size: false
  batch_size: 32
