# @package _global_
defaults:
  - _default
model:
  transformer:
    n_layers: 8
  session_embed_token_count: 8
dataset:
  datasets:
  - observation_.*
  - ortho_.*
  - fbc_.*
  - unstructured_.*
  - pitt_co.*
  # Our "test set"
  exclude_datasets:
  - observation_CRS02bLab_session_19.* #
  - observation_CRS07Lab_session_15.*
  - observation_CRS07Lab_session_16.*
  # There are at least 4 test sessions for CRS07 and 8 for CRS02bLab
train:
  autoscale_batch_size: false
  batch_size: 64
  accumulate_batches: 2
load_from_id: human_8l_8s-mbbng1dw # interrupted bc i'm dumb