# @package _global_
defaults:
  - /model: flat_enc_dec
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  hidden_size: 128
  task:
    mask_ratio: 0.8
    # tasks:
    # - ModelTask.infill
    # metrics:
    # - Metric.bps
  neurons_per_token: 8
dataset:
  max_tokens: 4096 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1

  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 8

  max_channels: 104
  bin_size_ms: 20
  datasets:
  - odoherty_rtt-Loco.*
  - odoherty_rtt-Indy-20161005_06
  # - odoherty_rtt-Indy-20161014_04 # one other full one for reference
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
# train:
  # autoscale_batch_size: false
  # batch_size: 64 # restrict due to small dataset
sweep_cfg: lr_and_dropout