# @package _global_

defaults:
  - /model: rnn
  - /dataset: base
model:
  task:
    decode_normalizer: './data/zscore_h1_7d.pt'
dataset:
  max_length_ms: 4000
  max_tokens: 8192
  explicit_alias_to_session: true

  neurons_per_token: 32
  max_channels: 176
  max_arrays: 1

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  - DataKey.bhvr_mask
  datasets:
  - falcon_FALCONH1-S0_.*_calib
  - falcon_FALCONH1-S1_.*_calib
  - falcon_FALCONH1-S2_.*_calib
  - falcon_FALCONH1-S3_.*_calib
  - falcon_FALCONH1-S4_.*_calib
  - falcon_FALCONH1-S5_.*_calib
  - falcon_FALCONH1-S6_.*_oracle
  - falcon_FALCONH1-S7_.*_oracle
  - falcon_FALCONH1-S8_.*_oracle
  - falcon_FALCONH1-S9_.*_oracle
  - falcon_FALCONH1-S10_.*_oracle
  - falcon_FALCONH1-S11_.*_oracle
  - falcon_FALCONH1-S12_.*_oracle
  eval_ratio: 0
  behavior_dim: 7

train:
  max_batch_size: 8
  batch_size: 8
  patience: 250
  early_stop_metric: val_kinematic_r2
  autoscale_batch_size: true
effective_bsz: 8

fragment_datasets: True

sweep_cfg: 'rnn_basic'
sweep_mode: 'grid'