# @package _global_

tag: maze_small_patience

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_small
  nlb_maze:
    heldout_neurons: 35
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
model:
  dropout: 0.8
  transformer:
    dropout: 0.8
    n_heads: 2
    n_layers: 4
  task:
    tasks:
    - ModelTask.infill
    - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    - Metric.co_bps
    - Metric.block_co_bps
train:
  patience: 15000
# This one runs the most risk of autoscale being whole dataset; probably worth capping batch size...