# @package _global_
defaults:
  - /model: flat_enc_dec
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  task:
    mask_ratio: 0.8
  neurons_per_token: 2
dataset:
  max_tokens: 4096 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1

  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 2

  datasets:
  - odoherty_rtt-Indy.* # Note we're just using indy here.
  - mc_rtt
  # - mc_maze.*
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  # - mc_rtt
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 20
  max_channels: 138
  # max_channels: 98
