# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  neurons_per_token: 4
  causal: true
  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  decoder_layers: 4
  task:
    decode_separate: True
    behavior_lag: 120
dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 4
  max_channels: 280

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  # - odoherty_rtt-Indy-20160624_03
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  # - odoherty_rtt-Indy-20160624_03

init_from_id: indy_causal-4i8yc4bc
init_tag: val_loss

# # ! New, testing regularization strategies
train:
  batch_size: 2
  autoscale_batch_size: false
  accumulate_batches: 32 # simulate 4x gpu
