# @package _global_

defaults:
  - /model: pretrain_2x # equivalent to flat_enc_dec without flattening
  - /dataset: base
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.5 # for efficiency
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
dataset:
  max_arrays: 1
  max_channels: 288
  datasets:
  - odoherty_rtt-Loco.*
train:
  patience: 250 # Extra generous patience.
  autoscale_batch_size: False
  batch_size: 256

notes: "Sorted, transfer loco."
seed: 3