# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /model/task:
    - bhvr_decode_flat
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  causal: True

  task:
    task_weights: [1.0, 1.0]
    # blacklist_session_supervision: ['observation_P2Lab_session_1926_set.*']
    mask_ratio: 0.5 # don't make this too hard...
    decode_normalizer: pitt_obs_zscore.pt

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  tune_decay: 0.75 # per Kaiming MAE

dataset:
  max_arrays: 2

  eval_ratio: 0.2
  neurons_per_token: 16
  max_channels: 192

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - observation_.*
  # exclude_datasets:
  # - observation_P2Lab_session_1926.* # For later tuning pilot
  # - observation_P2Lab_session_1926_set_5.*

  eval_datasets:
  - observation_P2Lab_session_1926_set_5.*

train:
  max_batch_size: 16
init_from_id: bci_pt_causal-21wye93c
init_tag: val_loss