# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 12
    pre_norm: true
  hidden_size: 384

  task:
    mask_ratio: 0.3
  neurons_per_token: 8

dataset:
  neurons_per_token: 8
  max_tokens: 8192
  max_channels: 288
  max_arrays: 2

  datasets:
  - churchland_maze.*
  - churchland_misc.*
  # - P2Home.data.*
  - odoherty_rtt.*
  - mc_maze$
  - dyer_co.*
  - gallego_co.*
  eval_datasets:
  - mc_maze$
train:
  autoscale_batch_size: false
  batch_size: 64 # uses 4 80G gpus -> 256
notes: "vs m3_150k for 32"
load_from_id: f8_150k-rq54iw9y # killed in first 4 hours lol...
# autoscale bsz = 32 on 40G