# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - joint_bhvr_decode_flat
  # - /train: finetune
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  task:
    task_weights: [1.0, 2000.0]
    behavior_lag: 120
    decode_time_pool: "mean"

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  # scale_limit_per_eval_session: 100
  # scale_limit_per_session: 0

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - CRS02bHome.data.*

  eval_datasets:
    - CRS02bHome.data.00437

  pitt_co:
    arrays:
    - CRS02b-lateral_m1
    - CRS02b-medial_m1
train:
  patience: 200
  autoscale_batch_size: false
  batch_size: 32
# init_from_id: reach_80000-qp92sqlc
# init_tag: val_loss
