# @package _global_
tag: dandi

defaults:
  - /model: pretrain_2x
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  # TODO no task embed strategy yet
  transformer:
    dropout: 0.1
  hidden_size: 256
  dropout: 0.1
  # readin_strategy: EmbedStrat.unique_project
  # readout_strategy: EmbedStrat.unique_project
dataset:
  bin_size_ms: 5
  max_channels: 137
  max_arrays: 2
  max_length_ms: 1500
  datasets:
  - churchland_maze_jenkins.*
  eval_datasets:
  - 'churchland_maze_jenkins-0'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 96
sweep_cfg: base
