# @package _global_
tag: factor_rtt_causal

defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  task:
    tasks: [ModelTask.next_step_prediction]

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 8
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true
dataset:
  max_channels: 104
  bin_size_ms: 20
  datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  - 'odoherty_rtt-Indy-20160.*'
  # odoherty_rtt-Indy-20161006_02 - holdout for decoding eval
  # - 'odoherty_rtt-Indy-20161006.*'
  - 'odoherty_rtt-Indy-20161007.*'
  - 'odoherty_rtt-Indy-2016101.*'
  - 'odoherty_rtt-Indy-2016102.*'
  - 'odoherty_rtt-Indy-201612.*'
  - 'odoherty_rtt-Indy-2017.*'
  - 'mc_rtt'
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject