# @package _global_

tag: gallego_chewie_single

defaults:
  - /model: pretrain
  - /train: pretrain
dataset:
  datasets:
  - Chewie_CO_20150313
  # - Chewie_CO.*
  # - Mihili_CO.*
  data_keys:
  - DataKey.spikes
  max_channels: 211
  max_arrays: 2
  max_length_ms: 5400
  bin_size_ms: 30
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.1
  transformer:
    dropout: 0.1
    n_heads: 2
    n_state: 256
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256

  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 256
  readout_dim: 256

  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
train:
  batch_size: 32
  # TODO need to chop Gallego, current max length is 500 which is 15s...