# @package _global_

tag: jenkins_misc_stitch

defaults:
  - /model: pretrain_2x
  - /dataset: maze
  - /train: pretrain
dataset:
  datasets:
  - churchland_misc_jenkins-*
  eval_datasets:
  - churchland_misc_jenkins-10cXhCDnfDlcwVJc_elZwjQLLsb_d7xYI
  data_keys:
  - DataKey.spikes
  max_channels: 96
  max_arrays: 2
  max_length_ms: 3000
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
  hidden_size: 256

  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 256
  readout_dim: 256
train:
  batch_size: 32
sweep_cfg: base