# @package _global_
tag: maze_jenkins_init

defaults:
  - /model: pretrain_2x
  - /dataset: maze
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add
  init_flags: True
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session

sweep_cfg: 'base'