# @package _global_

tag: maze_nlb_stitch

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20
model:
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 128
  readout_dim: 128
  dropout: 0.4
  transformer:
    dropout: 0.4
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
