# @package _global_

tag: maze_med

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_med
  eval_datasets:
  - mc_maze_medium
  nlb_maze:
    heldout_neurons: 38
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
model:
  dropout: 0.8
  transformer:
    dropout: 0.8
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    - Metric.co_bps
    - Metric.block_co_bps
train:
  patience: 5000