# @package _global_

tag: maze_small

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_small
model:
  dropout: 0.85
  transformer:
    dropout: 0.85