# @package _global_

tag: maze_nlb_256

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  # nlb_maze:
    # heldout_neurons: 40
  data_keys:
  - DataKey.spikes
  # - DataKey.heldout_spikes
train:
  batch_size: 192
model:
  transformer:
    n_state: 256
    n_heads: 2
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  dropout: 0.2
  task:
    tasks:
    - ModelTask.infill
    # - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    # - Metric.co_bps
    # - Metric.block_co_bps