# @package _global_
tag: maze_all

defaults:
  - /model: pretrain
  - /dataset: maze
  - /train: pretrain

model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
dataset:
  eval_datasets:
  - mc_maze_medium