# @package _global_
tag: maze_jenkins

defaults:
  - /model: pretrain
  - /dataset: maze_nlb
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  max_arrays: 2
train:
  accumulate_batches: 2
  batch_size: 128