# @package _global_
tag: maze_jenkins_stitch

defaults:
  - /model: pretrain
  - /dataset: maze
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add

  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 128
  readout_dim: 128
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session