# @package _global_
tag: maze_jenkins_ctx_out

defaults:
  - /model: pretrain_2x
  - /dataset: maze
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add
  readout_strategy: EmbedStrat.contextual_mlp
  readin_compress: False
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session

# sweep_cfg: 'base'