# @package _global_
tag: maze

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
model:
  readin_strategy: EmbedStrat.token
  dropout: 0.5
  transformer:
    dropout: 0.4
  task:
    mask_ratio: 0.25
dataset:
  datasets:
  - mc_maze$
  max_channels: 137
train:
  epochs: 5000
  batch_size: 128
  patience: 500 # batches are smaller