# @package _global_

tag: maze_nlb_stitch_out_nohead

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  # nlb_maze:
    # heldout_neurons: 40
  data_keys:
  - DataKey.spikes
  # - DataKey.heldout_spikes
model:
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 128
  readout_dim: 0
  dropout: 0.4
  transformer:
    dropout: 0.4
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    # - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    # - Metric.co_bps
    # - Metric.block_co_bps
    unique_no_head: True
