# @package _global_

tag: maze_med

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_med
model:
  dropout: 0.7
  transformer:
    dropout: 0.7