# @package _global_
tag: maze_jenkins_stitch_ablate

defaults:
  - /model: pretrain_2x
  - /dataset: maze
  - /train: pretrain

model:
  session_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session

# sweep_cfg: 'base'
# Q: Is stitching all you need? I'm assuming there's more nonlinear distinctions b/n ctxs