# @package _global_
tag: maze_jenkins_t64

defaults:
  - /model: pretrain_2x
  - /dataset: maze
  - /train: pretrain

model:
  session_embed_token_count: 64
  array_embed_strategy: EmbedStrat.token_add
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session

# sweep_cfg: 'base'