# @package _global_
tag: maze_jenkins_ctx

defaults:
  - /model: pretrain
  - /dataset: maze
  - /train: pretrain

model:
  array_embed_strategy: EmbedStrat.token_add

  readin_strategy: EmbedStrat.contextual_mlp
  readout_strategy: EmbedStrat.contextual_mlp
  readin_compress: False
  readin_dim: 128
  readout_dim: 128
  # task:
  #   unique_no_head: True
dataset:
  datasets:
  - churchland_maze_jenkins.*
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  meta_keys:
  - MetaKey.unique
  - MetaKey.array
  - MetaKey.session