# @package _global_

tag: nitschke_single

defaults:
  - /model: pretrain
  - /dataset: maze
  - /train: pretrain
dataset:
  datasets:
  - churchland_misc_nitschke-1D8KYfy5IwMmEZaKOEv-7U6-4s-7cKINK
  data_keys:
  - DataKey.spikes
  max_channels: 96
  max_arrays: 2
  max_length_ms: 3000
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
  dropout: 0.5
  transformer:
    dropout: 0.5
    n_heads: 2
    n_state: 256
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256

  # readin_strategy: EmbedStrat.unique_project
  # readout_strategy: EmbedStrat.unique_project
  # readin_compress: False
  # readin_dim: 256
  # readout_dim: 256
train:
  batch_size: 32
  accumulate_batches: 2