# @package _global_
tag: rtt_indy_sans_add

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  session_embed_strategy: EmbedStrat.token_add
  subject_embed_strategy: EmbedStrat.token_add
  array_embed_strategy: EmbedStrat.token_add

dataset:
  datasets: ['odoherty_rtt-Indy.*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject