# @package _global_
tag: rtt_indy_m1

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
dataset:
  datasets:
  - mc_rtt
  - odoherty_rtt-Indy.*
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject