# @package _global_
tag: rtt_all_sans

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add

dataset:
  datasets: ['odoherty_rtt*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject