# @package _global_
tag: rtt_indy2_noembed

defaults:
  - /model: pretrain_small
  - /dataset: rtt_nlb
  - /train: nlb
model:
  session_embed_strategy: EmbedStrat.none
  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  dropout: 0.6
  transformer:
    dropout: 0.6
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets:
  - odoherty_rtt-Indy-20161005_06
  - odoherty_rtt-Indy-20161014_04
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1