# @package _global_
tag: rtt_loco_512_stitch

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.1
  transformer:
    dropout: 0.1
    n_heads: 2
    n_state: 512
  hidden_size: 512
  session_embed_size: 512
  subject_embed_size: 512
  array_embed_size: 512

  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 512
  readout_dim: 512

  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets:
  - odoherty_rtt-Loco.*
  # - odoherty_rtt-Indy-20161014_04
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1