# @package _global_
tag: rtt_indy_loco_d03

defaults:
  - /model: pretrain_small
  - /dataset: rtt_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.3
  transformer:
    dropout: 0.3
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets:
  - odoherty_rtt-Indy-20161005_06
  - odoherty_rtt-Loco-20170215_02
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1