# @package _global_
tag: rtt_nlb_infill_only

defaults:
  - /model: pretrain_small
  - /dataset: rtt_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.7
  transformer:
    dropout: 0.7
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
dataset:
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject