# @package _global_
tag: rtt_all_sans_add

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  session_embed_strategy: EmbedStrat.token_add
  subject_embed_strategy: EmbedStrat.token_add
  array_embed_strategy: EmbedStrat.token_add
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets: ['odoherty_rtt*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  patience: 0
load_from_id: rtt_all_sans_add-1tecv06l
