# @package _global_
tag: rtt_all

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add

dataset:
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1