# @package _global_
tag: rtt_indy_ablate

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  session_embed_strategy: EmbedStrat.none
  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  transformer:
    n_state: 256
    dropout: 0.1
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  dropout: 0.1

  # readin_strategy: EmbedStrat.unique_project
  # readout_strategy: EmbedStrat.unique_project
  # readin_compress: False
  # readin_dim: 256
  # readout_dim: 256
dataset:
  datasets: ['odoherty_rtt-Indy.*']
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 256