# @package _global_
tag: rtt_indy_512

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  transformer:
    n_state: 512
    dropout: 0.1
  hidden_size: 512
  session_embed_size: 512
  subject_embed_size: 512
  array_embed_size: 512
  dropout: 0.1
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets: ['odoherty_rtt-Indy.*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 256 # 4 GPU