# @package _global_
tag: rtt_indy_unique_32

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  readin_strategy: EmbedStrat.unique_project
  readin_dim: 32
  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  transformer:
    n_state: 256
    dropout: 0.1
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  dropout: 0.1
  task:
    linear_head: True
dataset:
  datasets: ['odoherty_rtt-Indy.*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 256