# @package _global_
tag: rtt_loco_d2_2x

defaults:
  - /model: pretrain_small
  - /dataset: rtt_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  transformer:
    n_state: 256
    dropout: 0.1
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets:
  # - odoherty_rtt-Loco-20170210_03
  - odoherty_rtt-Loco-20170213_02
  # - odoherty_rtt-Loco-20170214_02
  # - odoherty_rtt-Loco-20170215_02
  # - odoherty_rtt-Loco-20170216_02
  # - odoherty_rtt-Loco-20170217_02
  # - odoherty_rtt-Loco-20170227_04
  # - odoherty_rtt-Indy-20161014_04
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
train:
  batch_size: 256