# @package _global_
tag: rtt_all_unique

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  readin_strategy: EmbedStrat.unique_project
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  transformer:
    n_state: 256
    dropout: 0.1
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  dropout: 0.1
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
    - Metric.all_loss
dataset:
  datasets: ['odoherty_rtt*']
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 256