# @package _global_
defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  transformer:
    n_state: 256
    dropout: 0.1
  hidden_size: 256
  session_embed_size: 256
  subject_embed_size: 256
  array_embed_size: 256
  dropout: 0.1
  # readin_strategy: EmbedStrat.contextual_mlp
  # readout_strategy: EmbedStrat.contextual_mlp
  readin_compress: False
  readin_dim: 256
  readout_dim: 256
dataset:
  bin_size_ms: 5
  datasets:
  - 'odoherty_rtt-Indy.*'
  - 'mc_rtt'
  eval_datasets:
  - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 512