# @package _global_
tag: rtt_indy_nlb

defaults:
  - /model: pretrain_small
  - /dataset: rtt_nlb
  - /train: nlb
model:
  readin_strategy: EmbedStrat.unique_project
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.6
  transformer:
    dropout: 0.6
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
dataset:
  datasets:
  - odoherty_rtt-Indy-20161005_06
  - mc_rtt
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1