# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /model/task:
    - bhvr_decode_flat
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  causal: True

  task:
    decode_time_pool: "mean"
    decode_normalizer: pitt_obs_zscore.pt

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - observation_.*
  exclude_datasets:
  - observation_CRS02bLab_session_1926.*
  eval_datasets:
  - observation_CRS02bLab_session_1926_set_5.*

train:
  patience: 2000
  autoscale_batch_size: false
  batch_size: 16
# init_from_id: bci_pt-qz71ene9
init_tag: val_loss