# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  task:
    task_weights: [1.0, 2000.0]
    behavior_lag: 0
    decode_time_pool: "mean"
    decode_normalizer: pitt_obs_zscore.pt

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - CRS02bHome.data.00329
  - CRS02bHome.data.00336
  - CRS02bHome.data.00339
  - CRS02bHome.data.00345
  - CRS02bHome.data.00360
  - CRS02bHome.data.00371
  - CRS02bHome.data.00402
  - CRS02bHome.data.00422
  - CRS02bHome.data.00424
  - CRS02bHome.data.00437
  - CRS02bHome.data.00445

  eval_datasets:
  - CRS02bHome.data.00445
  # - observation_CRS02bLab_session_1926.*

train:
  patience: 2000
  autoscale_batch_size: false
  batch_size: 32 # happen to be using 40G this run, 32 x 4
init_from_id: bci_pt-qz71ene9
init_tag: val_loss
notes: "Regress to Angelica's datasets, where we previously got nontrivial R2"