# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  # causal: True
  transformer:
    pre_norm: true

  neurons_per_token: 8

  task:
    mask_ratio: 0.75
    tasks:
    - ModelTask.shuffle_infill
    metrics: []
dataset:
  max_tokens: 2048
  neurons_per_token: 8
  max_arrays: 1
  bin_size_ms: 20
  serve_tokenized: true
  serve_tokenized_flat: true
  max_channels: 104
  eval_datasets:
  - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
sweep_cfg: lr