# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat

dataset:
  datasets:
  - odoherty_rtt-Loco.*
  odoherty_rtt:
    arrays: ['Indy-M1', 'Loco-M1']
    include_sorted: False
model:
  causal: true
  task:
    mask_ratio: 0.5
  neurons_per_token: 32
  subject_embed_strategy: EmbedStrat.token
train:
  patience: 250