# @package _global_

defaults:
  - _default
dataset:
  scale_limit: 800
train:
  autoscale_batch_size: false
  batch_size: 128
model:
  hidden_size: 128 # Historical lower limit, should works fine for <1K.