# @package _global_

# Really just a test of heterogeneity throughput rather than any specific win; can compare with scores in just Pitt

defaults:
  - /model: flat_enc_dec
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  # causal: True

  transformer:
    n_layers: 12

  neurons_per_token: 4
  hidden_size: 256

  task:
    mask_ratio: 0.8
    tasks:
    - ModelTask.shuffle_infill
    # - ModelTask.kinematic_decoding
    metrics: []
    # - Metric.kinematic_r2

  # lr_init: 1e-3
  lr_init: 6e-4
  lr_ramp_steps: 50
dataset:
  max_tokens: 4096
  max_length_ms: 2000
  max_arrays: 2
  bin_size_ms: 20
  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 4
  max_channels: 192 # 2 x 96... this should also cover Dyer.
  datasets:
  - churchland_maze.*
  - churchland_misc.*
  - CRS02bHome.data.*
  - dyer_co.*

  # - mc_rtt
  eval_datasets:
  - CRS02bHome.data.00437
  # - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject

train:
  batch_size: 4
  # batch_size: 8
  autoscale_batch_size: false # multi-gpu
