# @package _global_
defaults:
  - _default

dataset:
  scale_limit_per_eval_session: 20
  datasets:
  - odoherty_rtt-Indy-20160627_01
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01
train:
  batch_size: 4 # RIP
fragment_datasets: False
inherit_tag: unsup_3200-frag-odoherty_rtt-Indy-20160627_01-sweep-simpler_lr_sweep