# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.5 # for efficiency
  neurons_per_token: 32