# @package _global_

# mc_rtt targeting

defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  causal: True

  transformer:
    n_layers: 12
  neurons_per_token: 16
  hidden_size: 384

  task:
    mask_ratio: 0.5
    tasks:
    - ModelTask.shuffle_infill
    # - ModelTask.kinematic_decoding
    metrics: []
    # - Metric.kinematic_r2
dataset:
  max_tokens: 4096
  max_length_ms: 2000
  max_arrays: 2
  bin_size_ms: 20
  neurons_per_token: 16
  max_channels: 288
  datasets:
  - churchland_maze.*
  - churchland_misc.*
  # - CRS02bHome.data.*
  - odoherty_rtt.*
  - mc_maze.* # dropped bc I'm sleepy and the data isn't ready
  - dyer_co.*
  # - mc_rtt
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  # - CRS02bHome.data.00437 # using this as a convenient marker where we already have 20ms experiments
  # - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
train:
  autoscale_batch_size: false
  batch_size: 16
