# @package _global_
tag: dandi
# small in time
defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  # spike_embed_style: EmbedStrat.token
  # neurons_per_token: 16
  # hidden_size: 256
  # transform_space: true
  # transformer:
  #   factorized_space_time: true
dataset:
  max_arrays: 1
  churchland_maze:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
  datasets:
  - churchland_maze_jenkins.*
  eval_datasets:
  - 'churchland_maze_jenkins-0'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 20

  max_channels: 144

# disabled 2/5/13 for comparing with ablation
# train:
#   batch_size: 64
#   # accumulate_batches: 1
#   accumulate_batches: 4
#   autoscale_batch_size: false
# sweep_cfg: base