# @package _global_

defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none

  transformer:
    n_layers: 12
  hidden_size: 384

  task:
    mask_ratio: 0.1
    query_heldout: 45 # mc_maze maxed at this
    metrics:
    - Metric.co_bps
    - Metric.block_co_bps
  neurons_per_token: 32

  # lr_init: 5e-5
  # lr_ramp_steps: 1000
  # lr_decay_steps: 10000
  # accelerate_new_params: 10.0
  # tune_decay: 0.75 # per Kaiming MAE

dataset:
  neurons_per_token: 32
  max_tokens: 8192
  max_length_ms: 2000
  max_arrays: 2

  bin_size_ms: 20
  max_channels: 288
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_large

  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
train:
  patience: 50000
  # autoscale_batch_size: false
  # batch_size: 32
init_from_id: base_f32_150k_acausal-viexqpg7
init_tag: val_loss