# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none

  causal: False

  transformer:
    n_layers: 12
  hidden_size: 384

  task:
    mask_ratio: 0.1
  neurons_per_token: 32

dataset:
  neurons_per_token: 32
  max_tokens: 8192
  max_length_ms: 2000
  max_arrays: 2

  bin_size_ms: 20
  max_channels: 288
  datasets:
  - churchland_maze.*
  - churchland_misc.*
  # - P2Home.data.*
  - odoherty_rtt.*
  - mc_maze.*
  - dyer_co.*
  - gallego_co.*

train:
  autoscale_batch_size: false
  batch_size: 32
init_from_id: base_f32_150k_acausal-viexqpg7
init_tag: val_loss