# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 1
  # task_embed_strategy: EmbedStrat.token
  # subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 6
  hidden_size: 128

  task:
    mask_ratio: 0.25
  neurons_per_token: 32

dataset:
  neurons_per_token: 32
  max_tokens: 8192
  max_length_ms: 2000
  max_arrays: 2

  bin_size_ms: 20
  max_channels: 288
  datasets:
  # - churchland_maze.*
  # - churchland_misc.*
  # - P2Home.data.*
  # - odoherty_rtt.*
  - mc_maze.*
  # - dyer_co.*
  # - gallego_co.*
  exclude_datasets:
  - mc_maze_med
train:
  autoscale_batch_size: false
  batch_size: 64
