# @package _global_
# Testing for zero shot supervised transfer
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  session_embed_strategy: EmbedStrat.none
  subject_embed_strategy: EmbedStrat.none
  neurons_per_token: 16
  causal: true

  task:
    behavior_lag: 120
    decode_time_pool: "mean"

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - odoherty_rtt-Indy-20160407_02
  - odoherty_rtt-Indy-20160411_01
  - odoherty_rtt-Indy-20160411_02
  - odoherty_rtt-Indy-20160418_01
  - odoherty_rtt-Indy-20160419_01
  - odoherty_rtt-Indy-20160420_01
  # Test 0426 for zero shot
  # Swap to full unsorted arrays
  # odoherty_rtt:
    # arrays: ["Indy-M1_all", "Loco-M1_all"]
    # include_sorted: True
# train:
#   autoscale_batch_size: false
#   batch_size: 32
load_from_id: rtt_less_stable-j08z0tli