# @package _global_
# Controlled evaluation
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  # - /model/task:
    # - bhvr_decode_flat
  # - /train: finetune
  - /dataset: flat
model:
  # Well we already know from early scaling experiments that embed strategies promotes faster convergence
  # And doesn't hurt peak performance; and it must be explicitly through transfer mxsms, so I don't see why we shouldn't allow it.
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token

  neurons_per_token: 16

  task:
    behavior_lag: 120
    decode_time_pool: "mean"

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  scale_limit_per_eval_session: 100
  scale_limit_per_session: 0

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  # - DataKey.bhvr_vel
  datasets:
  - mc_maze$
  - dyer_co.*
  - churchland_misc_reggie-1413W9XGLJ2gma1CCXpg1DRDGpl4-uxkG
  - odoherty_rtt-Indy-20160627_01

  # Other multi datasets scale radial out, preferring backward
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01

  churchland_misc:
    arrays: ["Reggie-M1", "Nitschke-M1", "Jenkins-M1"]
train:
  patience: 200
