# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  # - /model/task:
    # - bhvr_decode_flat
  # - /train: finetune
  - /dataset: flat
model:
  hidden_size: 384
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  task:
    behavior_lag: 120
    decode_time_pool: "mean"

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  scale_limit_per_eval_session: 100
  scale_limit_per_session: 0

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  # - DataKey.bhvr_vel
  datasets:
  - mc_maze$
  - dyer_co.*
  - churchland_misc.*
  - odoherty_rtt-Indy-20160627_01

  # Other multi datasets scale radial out, preferring backward
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01

  churchland_misc:
    arrays: ["Reggie-M1", "Nitschke-M1", "Jenkins-M1"]
train:
  patience: 200
  autoscale_batch_size: false
  batch_size: 32
  accumulate_batches: 2
