# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 12
    pre_norm: true
  hidden_size: 384

  task:
    mask_ratio: 0.3
  neurons_per_token: 32

dataset:
  neurons_per_token: 32
  max_tokens: 8192
  max_channels: 288
  max_arrays: 2

  datasets:
  - churchland_maze.*
  - churchland_misc.*
  # - CRS02bHome.data.*
  - odoherty_rtt.*
  - mc_maze$
  - dyer_co.*
  - gallego_co.*
  eval_datasets:
  - mc_maze$
notes: "vs bsz256, since we have autoscale"