# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_CRS02bLab_session_18.*
  - observation_CRS02bLab_session_19.*
train:
  autoscale_batch_size: false
  batch_size: 32

# This one has a smaller source to build a decoder - in lieu of intra-session stable decoder