# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: false
  batch_size: 16
model:
  task:
    tasks: [ModelTask.kinematic_decoding]
    metrics: [Metric.kinematic_r2]
    decode_strategy: EmbedStrat.token
    decode_separate: true
    freeze_backbone: True
inherit_tag: human_obs