# @package _global_
defaults:
  - _default
model:
  task:
    behavior_tolerance: 0.5 # this is in z-score units, at least for Pitt
train:
  autoscale_batch_size: false
  batch_size: 16
inherit_exp: scale_decode
inherit_tag: session_cross