# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: false
  batch_size: 16
  accumulate_batches: 4
model:
  task:
    blacklist_session_supervision:
    - observation_.*
inherit_exp: scale_decode
inherit_tag: session_cross