# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 16
  causal: true

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  tune_decay: 0.75 # per Kaiming MAE

  task:
    behavior_lag: 120

    freeze_backbone: true
    freeze_all: true
dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - mc_rtt
  eval_datasets:
  - mc_rtt
  # Has ~1K trials, use 800 trials as a "super high regime" fine tuning and then TODO tweak scale ratio
  eval_ratio: 0.2
  scale_ratio: 1.0

init_from_id: indy_causal_joint-66optips
init_tag: val_loss
notes: "supervised ctrl for token tuning"