# @package _global_
tag: indy_scratch_decode

defaults:
  - /model: pretrain
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  task:
    tasks: [ModelTask.kinematic_decoding]
    metrics: [Metric.kinematic_r2]
  readin_compress: false
  causal: True
dataset:
  max_arrays: 1
  bin_size_ms: 20
  max_channels: 104
  datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  - 'odoherty_rtt-Indy-20160.*'
  # odoherty_rtt-Indy-20161006_02 - holdout for decoding eval
  # - 'odoherty_rtt-Indy-20161006.*'
  - 'odoherty_rtt-Indy-20161007.*'
  - 'odoherty_rtt-Indy-2016101.*'
  - 'odoherty_rtt-Indy-2016102.*'
  - 'odoherty_rtt-Indy-201612.*'
  - 'odoherty_rtt-Indy-2017.*'
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
# init_from_id: rtt_causal-ankuy3ai
train:
  batch_size: 32
  autoscale_batch_size: false