# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 5

  max_channels: 140
  neurons_per_token: 4
  max_tokens: 4096
  serve_tokenized: true
  serve_tokenized_flat: true
model:
  dropout: 0.1
  transformer:
    dropout: 0.1
    n_heads: 2
  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  hidden_size: 128
  neurons_per_token: 4
  transform_space: true
