# @package _global_

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 5

  max_channels: 140
model:
  dropout: 0.1
  transformer:
    dropout: 0.1
    n_heads: 2
    factorized_space_time: false
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps

  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 4
  hidden_size: 128
  transform_space: true