# @package _global_
tag: ks_512

defaults:
  - /model: pretrain
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  # TODO no task embed strategy yet
  transformer:
    n_state: 512
    dropout: 0.2
  hidden_size: 512
  session_embed_size: 512
  subject_embed_size: 512
  array_embed_size: 512
  dropout: 0.2
  lr_init: 3e-3
dataset:
  bin_size_ms: 5
  max_channels: 137
  max_arrays: 2
  max_length_ms: 1500
  datasets:
  # Jenkins, Nitschke
  - churchland_maze.*
  - churchland_misc_nitschke.*
  - odoherty_rtt.*
  # Indy, Loco
  - mc_rtt
  - mc_maze.*
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 72
# load_from_id: ks_512-1a6f72z7