# @package _global_
tag: rtt_dandi_m1

defaults:
  - /model: pretrain_2x
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  # TODO no task embed strategy yet
  # readin_strategy: EmbedStrat.unique_project
  # readout_strategy: EmbedStrat.unique_project
dataset:
  bin_size_ms: 20
  max_channels: 98
  max_arrays: 1
  max_length_ms: 1500
  datasets:
  # Jenkins, Nitschke
  # - churchland_maze.*
  # - churchland_misc_nitschke.*
  - odoherty_rtt.*
  - churchland_maze.*
  # - churchland_misc.*
  # Indy, Loco
  - mc_rtt
  # - mc_maze.*
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  churchland_maze:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  churchland_misc:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
    - Reggie-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 192
sweep_cfg: large