# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: maze_nlb
  - /train: pretrain
model:
  hidden_size: 384
  task:
    mask_ratio: 0.8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 4
dataset:
  max_tokens: 4096 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1

  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 4

  datasets:
  - odoherty_rtt-Indy.*
  - mc_maze_medium
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20
  max_channels: 144
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  - MetaKey.task
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
sweep_cfg: lr_v3
sweep_trials: 4