# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.5 # for efficiency
  neurons_per_token: 32
  transformer:
    pre_norm: true
dataset:
  neurons_per_token: 32

  max_arrays: 1
  max_channels: 288

  scale_ratio: 1.0
  scale_limit_per_eval_session: 300 # no limit

  datasets:
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01

# Sweeps run on CRC, A100 40G GPUs. Clip bsz to 512
train:
  autoscale_batch_size: false
  batch_size: 512
sweep_cfg: base_v2
sweep_trials: 16