# @package _global_
tag: factor_rtt_maze_4

defaults:
  - /model: pretrain_2x
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 4
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true
dataset:
  neurons_per_token: 4
  bin_size_ms: 20
  # max_channels: 98
  # max_channels: 112
  max_channels: 140
  max_arrays: 1
  max_length_ms: 1000
  datasets:
  # Jenkins, Nitschke
  # - churchland_maze.*
  # - churchland_misc_nitschke.*
  - odoherty_rtt.*
  # - churchland_misc.*
  # Indy, Loco
  - mc_rtt
  - mc_maze.*
  eval_datasets:
  - 'mc_maze_medium'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  churchland_misc:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
    - Reggie-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 192
  # accumulate_batches: 8