# @package _global_
tag: factor_rtt_16_indyloco_loco
# For evaluating whether multi-subject transfer works for Loco
# Motivation: There's been no scaling improvements for Indy from adding loco.
# (hypothesis: because there's less data for Loco, we should see effects more in Loco)

defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 16
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true
dataset:
  serve_tokenized: False
  datasets:
  - 'odoherty_rtt.*'
  eval_datasets:
  - 'odoherty_rtt-Loco-20170215_02'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 20

  max_channels: 112