# @package _global_

tag: factor_churchland_nitschke_m1_1
# Motivation: Multi-subject tests on highly fairly heterogeneous tasks as well

defaults:
  - /model: pretrain_2x
  - /train: pretrain
dataset:
  datasets:
  - churchland_misc_nitschke.*
  eval_datasets:
  - churchland_misc_nitschke-1D8KYfy5IwMmEZaKOEv-7U6-4s-7cKINK
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20
  max_arrays: 1
  max_channels: 96
  max_length_ms: 1000
  churchland_misc:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
    - Reggie-M1
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  transformer:
    factorized_space_time: true
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 4
  transform_space: true