# @package _global_

tag: factor_maze_churchland_1

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  - churchland_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20
  max_arrays: 1
  max_channels: 137
  max_length_ms: 1500
  churchland_maze:
    arrays:
    - Nitschke-M1
    - Jenkins-M1
model:
  dropout: 0.4
  transformer:
    dropout: 0.4
    n_heads: 2
    factorized_space_time: true
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps

  array_embed_strategy: EmbedStrat.none
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 1
  hidden_size: 256
  transform_space: true
  # intentionally not serve_tokenized; expecting there's probably some regularizing effect...