# @package _global_

tag: st_maze_4

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20

  max_channels: 144
model:
  dropout: 0.4
  transformer:
    dropout: 0.4
    n_heads: 2
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps

  array_embed_strategy: EmbedStrat.none
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 4
  hidden_size: 256
  transform_space: true
