# Not meant to be thorough, just sanity check a few settings.
model:
  # Really the majority of experiments are about _data_
  # so `dataset` (or embedding strat) is the configured item, and we sweep other nuisance params
  # Nuisance parameters

  # TODO I really need to bind other sizes to this.
  # we will use a fixed 6-layer architecture for now, sweep hidden.
  hidden_size:
  - 128
  - 256
  - 384
  - 512
  - 768

  # lr init: 5e-4 is rznable for 10-30K datapts, unclear what the dynamic range needed is
  lr_init:
  - 5e-2
  - 5e-3
  - 5e-4
  - 5e-5
  weight_decay:
  - 1e-3
  - 1e-2
  - 5e-2
  dropout:
  - 0.3
  - 0.2
  - 0.1


  seed: [0, 1, 2]
  # Relative to other domains, we can afford to train multiple models quite cheaply (each only take a few hours initially), so let's ensure the validity of what we have at least on model random seed

  # Some fixed params
  # LR schedule (warmup and very slow cosine decay)