# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 8
dataset:
  datasets:
  - odoherty_rtt-Indy.*
  exclude_datasets:
  - odoherty_rtt-Indy-20160407_02 # First indy session
  - odoherty_rtt-Indy-20160627_01 # Original
  - odoherty_rtt-Indy-20161005_06
  - odoherty_rtt-Indy-20161026_03
  - odoherty_rtt-Indy-20170131_02 # Last indy sesison
train:
  batch_size: 256
  accumulate_batches: 2
load_from_id: f8-up0vzeww # this run was interrupted bc I'm dumb