# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 8
dataset:
  datasets:
  - odoherty_rtt-Loco.*
train:
  accumulate_batches: 2
  batch_size: 256