# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
dataset:
  max_arrays: 1
  max_channels: 288
  datasets:
  - mc_maze.*
  - dyer_co.*
  - gallego_co.*
  - churchland_misc_nitschke.*
notes: "Sorted, transfer task."