# @package _global_

defaults:
  - /model: pretrain_2x # equivalent to flat_enc_dec without flattening
  - /dataset: base
  - _default
model:
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
dataset:
  max_arrays: 1
  max_channels: 288
  datasets:
  - mc_maze.*
  - dyer_co.*
  - gallego_co.*
  - churchland_misc_nitschke.*