# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /model/task: joint_heldout_decode
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 24
    n_heads: 4
    pre_norm: true
    debug_force_nonlearned_position: true
  hidden_size: 512

  task:
    task_weights: [0, 1.]
    mask_ratio: 0.3
    query_heldout: 45
  neurons_per_token: 16

  weight_decay: 0.01
  lr_init: 5e-5
  accelerate_new_params: 1.0
  lr_schedule: 'fixed'
  # lr_ramp_steps: 100
  # lr_decay_steps: 300
  # lr_min: 1e-5

  # force_zero_mask: true
dataset:
  neurons_per_token: 16
  max_tokens: 8192
  max_channels: 288
  max_arrays: 2

  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
  datasets:
  - mc_maze_small
  # No eval set, just compare directly with the benchmark baselines
train:
  autoscale_batch_size: false
  batch_size: 64
  patience: 500
init_from_id: m3_150k-91lyoz89
init_tag: val_loss
notes: "Give this a shot."