# @package _global_

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_rtt
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
  bin_size_ms: 20
model:
  dropout: 0.7
  transformer:
    dropout: 0.7
    n_heads: 2
  task:
    task_weights: [1., 1.]
    tasks:
    - ModelTask.infill
    - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    - Metric.co_bps
    - Metric.block_co_bps
train:
  autoscale_batch_size: false
  batch_size: 64
  patience: 5000