# @package _global_

tag: maze_all_large_ft

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  accelerate_new_params: 10.0
dataset:
  datasets:
  - mc_maze_large
  max_arrays: 1
  nlb_maze:
    heldout_neurons: 40
    # small is 35, large is 40
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  readout_dim: 128

init_from_id: "maze_all-339tvoxc"
# init_from_id: "maze_all-307jsaky"
