# @package _global_

tag: maze_small_ft

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_small
  nlb_maze:
    heldout_neurons: 35
    # small is 35, large is 40

init_from_id: "maze_small-1kg4z08e"
