# @package _global_

tag: maze_large_ft

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze_large
  nlb_maze:
    heldout_neurons: 40
    # small is 35, large is 40
init_from_id: "maze_large-229sooya"
