# @package _global_

tag: rtt_nlb_ft

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: rtt_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  dropout: 0.7
  transformer:
    dropout: 0.7
    n_heads: 2
  task:
    tasks:
    - ModelTask.heldout_decoding
    metrics:
    - Metric.co_bps
    - Metric.block_co_bps
  # accelerate_new_params: 10.0
  lr_init: 5e-4
dataset:
  datasets:
  - mc_rtt
  max_arrays: 1
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject

init_from_id: "rtt_nlb_pt-35llyrnm"
