# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  bin_size_ms: 20

  max_channels: 140
  neurons_per_token: 140
  max_tokens: 2048
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  hidden_size: 128
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
  neurons_per_token: 4
  transform_space: true
