# @package _global_
defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # array_embed_strategy: EmbedStrat.token_add
  # causal: True

  encode_decode: true
  transform_space: true
  transformer:
    flat_encoder: true
    learnable_position: true
    max_trial_length: 250
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 8
  hidden_size: 256

  task:
    tasks:
    - ModelTask.infill
    # - ModelTask.kinematic_decoding
    metrics: []
    # - Metric.kinematic_r2
dataset:
  max_tokens: 2048
  max_arrays: 1
  bin_size_ms: 5
  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 8
  max_channels: 104
  eval_datasets:
  - 'mc_rtt'
  # - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject

train:
  accumulate_batches: 8