# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  hidden_size: 256
  transform_space: true
  neurons_per_token: 1
  task:
    mask_ratio: 0.25
dataset:
  max_tokens: 4096
  datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  - 'odoherty_rtt-Indy-20160.*'
  - 'odoherty_rtt-Indy-20161006.*'
  - 'odoherty_rtt-Indy-20161007.*'
  - 'odoherty_rtt-Indy-2016101.*'
  - 'odoherty_rtt-Indy-2016102.*'
  - 'odoherty_rtt-Indy-201612.*'
  - 'odoherty_rtt-Indy-2017.*'
  - 'mc_rtt'
  eval_datasets:
  - 'mc_rtt'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 5

  max_channels: 100
  neurons_per_token: 1
  serve_tokenized: true
  serve_tokenized_flat: true
train:
  # DDP doesn't support autoscale as of 2/6/23. Workflow is to manually launch a single GPU run; check batch size, load here.
  autoscale_batch_size: false
  batch_size: 2
