defaults:
  - _default
inherit_exp: pitt_v3/decode_online_bci
inherit_tag: human_P2_tune
tag: online_human_pt_unsup_broad
notes: "Unsupervised tuning of human-pt model, broad data."
model:
  closed_loop_crop_bins: 50 # safe default.
  # lr_init: 4e-5 # assuming broader batch size
  task:
    blacklist_session_supervision:
    - CRS.* # Assuming P4
    - crs.*
    # We still keep the extra task so the weights are kept in ckpt and can be loaded.
    # But we effectively neuter it by removing its loss. (Ignore R2 if you like)
train:
  autoscale_batch_size: True
  # batch_size: 16 # smaller batch sizes miraculously more useful...?
  max_batch_size: 128