# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
dataset:
  max_arrays: 1
  max_channels: 288