# @package _global_

defaults:
  - _default
model:
  session_embed_strategy: EmbedStrat.none
  subject_embed_strategy: EmbedStrat.none
  decoder_context_integration: 'cross_attn'
  task:
    decode_time_pool: ""
inherit_exp: arch/robust_unsort
inherit_tag: f32_noctx
notes: 'default strategy is mean pool 2 layer decoder'