# @package _global_

defaults:
  - _default
model:
  decoder_context_integration: 'cross_attn'
  task:
    decode_time_pool: ""
inherit_exp: arch/robust_unsort
inherit_tag: f32
notes: 'default strategy is mean pool 2 layer decoder'