# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /model/task:
    - bhvr_decode_flat
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 1
  # task_embed_strategy: EmbedStrat.token
  # subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 6
    # debug_force_nonlearned_position: True
  hidden_size: 128

  task:
    mask_ratio: 0.25
    behavior_lag: 120
  neurons_per_token: 32

  # force_zero_mask: True

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  tune_decay: 0.75 # per Kaiming MAE

dataset:
  nlb_maze:
    heldout_neurons: 45
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  neurons_per_token: 32
  max_tokens: 8192
  max_length_ms: 2000
  max_arrays: 2

  bin_size_ms: 20
  max_channels: 288
  datasets:
  # - churchland_maze.*
  # - churchland_misc.*
  # - CRS02bHome.data.*
  # - odoherty_rtt.*
  # - mc_maze.*
  - mc_maze_medium
  # - dyer_co.*
  # - gallego_co.*
  eval_datasets:
  - mc_maze_med
  eval_ratio: 0.2
train:
  autoscale_batch_size: false
  batch_size: 64
  patience: 500
init_from_id: maze_f32_scratch_b-a70ox05b
init_tag: val_loss