# @package _global_

defaults:
  - _default
dataset:
  datasets:
  - mc_maze.*
  - dyer_co.*
  - gallego_co.*
  - churchland_misc.*
  - churchland_maze.*
  - marino_.*
  # scale_limit: 4000

  - observation_.*
  - ortho_.*
  - fbc_.*
  - unstructured_.*
  - pitt_co.*
  exclude_datasets:
  - observation_CRS02bLab_session_19.* #
  - observation_CRS07Lab_session_15.*
  - observation_CRS07Lab_session_16.*
train:
  autoscale_batch_size: false
  accumulate_batches: 4
  batch_size: 128 # 4x80G -> effective 2048
model:
  transformer:
    n_layers: 16
notes: "Add human."
