# @package _global_
tag: rtt_joint_indy_ablate

defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  session_embed_strategy: EmbedStrat.none
  subject_embed_strategy: EmbedStrat.none
  array_embed_strategy: EmbedStrat.none
dataset:
  datasets:
  - 'odoherty_rtt-Indy-.*'
  - 'mc_rtt'
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 20
train:
  batch_size: 256
sweep_cfg: base