# @package _global_

# 4x2 transferring strategies
# first axis is weight update rules
# 1. freeze backbone
# 2. freeze everything but embedding
# 3. fine-tune with acceleration of novel params
# 4. fine-tune
# ? How should we

# second axis is whether we do it over full dataset or just target dataset

tag: rtt_indy_transfer_backbone_novel

defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
  task:
    freeze_backbone: true
dataset:
  datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  # - 'odoherty_rtt-Indy-20160.*'
  # - 'odoherty_rtt-Indy-20161006.*'
  # - 'odoherty_rtt-Indy-20161007.*'
  # - 'odoherty_rtt-Indy-2016101.*'
  # - 'odoherty_rtt-Indy-2016102.*'
  # - 'odoherty_rtt-Indy-201612.*'
  # - 'odoherty_rtt-Indy-2017.*'
  # - 'mc_rtt'
  eval_datasets:
  - 'odoherty_rtt-Indy-20161005_06'
  odoherty_rtt:
      arrays:
      - Indy-M1
      - Loco-M1
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 20
train:
  batch_size: 256
sweep_cfg: base

init_from_id: rtt_joint_indy_out-sweep-base-t5wtvgrm