# @package _global_
# ! Note: The experiments here directly rely on data preprocessed in the NDT3 codebase. 
# ! Preprocessing the raw datafiles in this codebase will yield slight differences due to different normalization mechanisms.

defaults:
  - /model: flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
model:
  lr_ramp_steps: 50
  lr_decay_steps: 1500
  lr_interval: epoch
  causal: true
  neurons_per_token: 32
  session_embed_strategy: EmbedStrat.none
  transformer:
    max_trial_length: 500 # 10 seconds
    n_layers: 6
  task:
    mask_ratio: 0.25 # for efficiency
    task_weights: [1.0, 1.0]
    decode_time_pool: ''
    decode_normalizer: '' # V5 - directly use NDT3 preprocessed data for inbuilt minmax norm
    # decode_normalizer: './data/zscore_calib_pitt_grasp_1d.pt' # TODO
  decoder_context_integration: 'cross_attn'
  dropout: 0.1
dataset:
  ignore_preprocess: True # ! Use NDT3 preproc
  bin_size_ms: 20
  max_length_ms: 10000 # Can't fit much more than this on the old GPUs this is running on, and nonefficient attn
  max_tokens: 8192 # expecting 6 tokens/bin x 500 bins = 3000 tokens
  # explicit_alias_to_session: true

  neurons_per_token: 32
  max_channels: 192
  max_arrays: 2

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  - DataKey.bhvr_mask
  datasets:
  - calib_pitt_grasp.*
  - eval_pitt_grasp.*
  eval_datasets:
  - eval_pitt_grasp.*
  eval_ratio: 1.0
  behavior_dim: 1
  pitt_co:
    # respect_trial_boundaries: True
    respect_trial_boundaries: False
    chop_size_ms: 1000 # Updated for parity with cursor_hard
    arrays:
      - "CRS02b-lateral_m1"
      - "CRS02b-medial_m1"
      - "CRS07-lateral_m1"
      - "CRS07-medial_m1"
      - "CRS08-lateral_m1"
      - "CRS08-medial_m1"

train:
  # max_batch_size: 64
  max_batch_size: 512
  # batch_size: 64
  batch_size: 512
  patience: 100 # Match NDT3 V5
  # patience: 250 # NDT3 V4
  early_stop_metric: val_kinematic_r2
effective_bsz: 512
sweep_cfg: full_scratch
# sweep_cfg: simple_scratch
sweep_mode: 'grid'
notes: 'Comparison with NDT3'