# @package _global_

defaults:
  - /train: single_session_exp1
  - /model/task:
    - bhvr_decode
dataset:
  eval_ratio: 0.1
  scale_limit_per_eval_session: 300

  datasets:
  - odoherty_rtt-Indy-20160407_02 # First indy session
  - odoherty_rtt-Indy-20160627_01 # Original
  - odoherty_rtt-Indy-20161005_06
  - odoherty_rtt-Indy-20161026_03
  - odoherty_rtt-Indy-20170131_02
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  odoherty_rtt:
    arrays: ['Indy-M1', 'Loco-M1']
    include_sorted: False
model:
  task:
    mask_ratio: 0.5 # pretty sure this is irrelevant
    behavior_lag: 120
  accelerate_new_params: 10.0 # We're introducing a whole new readout layer...
  lr_schedule: 'fixed'
inherit_exp: arch/robust_unsort_s2/tune
fragment_datasets: True

sweep_cfg: 'simpler_lr_sweep'
sweep_mode: 'grid'
seed: 2