# @package _global_
# Best way to test scaling would probably be
# take subsets of train, specifically 1, 1/2, 1/4, 1/8, 1/16, 1/32
# each of these trials are _large_, run on A100s (which fits ~bsz 16, Indy has ~1.8K x 16 trials)
defaults:
  - /model: flat_enc_dec
  - /dataset: flat
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  task:
    mask_ratio: 0.5 # 0.25 is quite costly, but we want to see long tail of improvements, so go over 0.8
  neurons_per_token: 4
dataset:
  max_tokens: 4096 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1
  scale_ratio: 1.0

  neurons_per_token: 4

  max_channels: 280
  bin_size_ms: 20
  datasets:
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06