# @package _global_
tag: test

model:
  task:
    task: ModelTask.infill
  readin_strategy: EmbedStrat.token
dataset:
  bin_size_ms: 5
  datasets:
  - mc_maze_small
  # - churchland_maze_jenkins-0
  data_keys:
  - "spikes"

  max_arrays: 2
  max_channels: 137
train:
  epochs: 100
  # epochs: 2000
  batch_size: 128