# @package _global_
tag: test

model:
  task:
    task: ModelTask.infill
  readin_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
dataset:
  bin_size_ms: 5
  datasets:
  - churchland_maze.*
  data_keys:
  - "spikes"

  max_arrays: 2
  max_channels: 137
train:
  epochs: 100
  # epochs: 2000
  batch_size: 128