# @package _global_
tag: maze_channel_padded

defaults:
  - /model:
    - pretrain
  - /dataset: maze_nlb
  - /train: nlb
model:
  readin_strategy: EmbedStrat.token
dataset:
  datasets:
  - 'mc_maze$'
  max_channels: 137
  max_arrays: 1