# @package _global_

tag: maze_all_small_ft

defaults:
  - /model:
    - finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
dataset:
  datasets:
  - mc_maze_small
  max_arrays: 1
  nlb_maze:
    heldout_neurons: 35
    # small is 35, large is 40
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  batch_size: 64 # 2 gpus

init_from_id: "maze_all-TODO"
