# @package _global_
tag: maze_no_embed

model:
  task:
    task: ModelTask.infill
  session_embed_strategy: EmbedStrat.none
dataset:
  bin_size_ms: 5
  datasets:
  - mc_maze_small
  data_keys:
  - "spikes"

train:
  epochs: 2000
  # max_channels: 140 # test # TODO