# @package _global_

tag: maze_jenkins_nlb_ft

defaults:
  - /model:
    - finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb
model:
  array_embed_strategy: EmbedStrat.token_add
  lr_init: 1e-3
  lr_ramp_steps: 5000
dataset:
  max_arrays: 1

init_from_id: "maze_jenkins-1k9xx5do"
