# @package _global_
tag: maze_jenkins_only_to_med_ft_faster

defaults:
  - /model: finetune
  - /model/task: nlb
  - /dataset: maze_nlb
  - /train: nlb

model:
  array_embed_strategy: EmbedStrat.token_add
  accelerate_new_params: 10.0
dataset:
  datasets:
  - mc_maze_medium
  max_arrays: 1
  nlb_maze:
    heldout_neurons: 38
    # small is 35, large is 40

init_from_id: "maze_jenkins_only-2a0baze7"