# @package _global_
tag: maze_med_lessmask

defaults:
  - /model: pretrain
  - /dataset: maze_nlb
  - /train: nlb
model:
  readin_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.25
dataset:
  datasets:
  - mc_maze_medium
  max_channels: 137
train:
  epochs: 5000
  batch_size: 128
  patience: 500 # batches are smaller