# @package _global_
tag: maze_channel_padded

model:
  task:
    task: ModelTask.infill
dataset:
  bin_size_ms: 5
  datasets:
  - mc_maze_small
  data_keys:
  - "spikes"

  max_channels: 140
train:
  epochs: 2000