# @package _global_
tag: maze_full

model:
  task:
    task: ModelTask.infill
  readin_strategy: EmbedStrat.token
dataset:
  bin_size_ms: 5
  datasets:
  - mc_maze_medium
  data_keys:
  - "spikes"

  max_channels: 137
train:
  epochs: 2000
  batch_size: 128
