# @package _global_
tag: rtt_frozen

model:
  task:
    task: ModelTask.heldout_decoding
    freeze_backbone: true
    metrics:
    - Metric.co_bps
    outputs:
    - Output.heldout_rates
  readin_strategy: EmbedStrat.token
  session_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  weight_decay: 1e-3
dataset:
  bin_size_ms: 5
  datasets:
  - mc_rtt
  max_channels: 98
  max_arrays: 1
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
train:
  patience: 50
  batch_size: 128

init_from_id: "rtt_all_m1_padded-3sguwwiv"