# @package _global_
tag: rtt_ft

model:
  task:
    task: ModelTask.heldout_decoding
    freeze_backbone: false
  readin_strategy: EmbedStrat.token
  session_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token
dataset:
  bin_size_ms: 5
  datasets:
  - mc_rtt
  max_channels: 98
  max_arrays: 1
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
train:
  steps: 1000
  batch_size: 128

init_from_id: "rtt_all_m1_padded-3sguwwiv"