# @package _global_
tag: rtt_indy_m1_padded

model:
  task:
    task: ModelTask.infill
  readin_strategy: EmbedStrat.token
  session_embed_strategy: EmbedStrat.token
dataset:
  bin_size_ms: 5
  datasets:
  - mc_rtt
  - odoherty_rtt-Indy.*
  odoherty_rtt:
    arrays:
    - Indy-M1
  max_channels: 98
  max_arrays: 1
train:
  steps: 10000
  batch_size: 512

