# @package _global_

tag: test4

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: nlb
dataset:
  datasets:
  # - dyer_co_mihi_1
  # - dyer_co_mihi_2
  # - dyer_co_chewie_1
  - dyer_co_chewie_2
  data_keys:
  - DataKey.spikes
model:
  # dropout: 0.8
  # transformer:
  #   dropout: 0.8
  #   n_heads: 2
  #   n_layers: 4
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
train:
  patience: 6000