# @package _global_
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
model:
  half_precision: False
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  task:
    mask_ratio: 0.8
  neurons_per_token: 8
dataset:
  max_tokens: 4096 # fit
  max_length_ms: 2000 # fit
  max_arrays: 1

  serve_tokenized: true
  serve_tokenized_flat: true
  neurons_per_token: 8

  max_channels: 104
  bin_size_ms: 20
  datasets:
  - odoherty_rtt-Indy.*
  # - odoherty_rtt-Indy-20161014_04
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
train:
  # batch_size: 64 # restrict due to small dataset
  patience: 200
# sweep_cfg: lr_and_dropout
# sweep_trials: 16 # likely more sensitive due to small size