# @package _global_
tag: maze_5_factor_1

defaults:
  - /model: pretrain_small
  - /dataset: maze_nlb
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 1
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true

  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
dataset:
  datasets:
  - mc_maze.*
  eval_datasets:
  - mc_maze_medium
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 5

  max_channels: 137
  # max_channels: 98
sweep_cfg: base