# @package _global_
tag: rtt_5_factor_8_cobps

defaults:
  - /model: pretrain_2x
  - /dataset: rtt
  - /train: pretrain

model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  task:
    tasks:
    - ModelTask.infill
    - ModelTask.heldout_decoding
    metrics:
    - Metric.bps
    - Metric.co_bps
    - Metric.block_co_bps
  accelerate_new_params: 10.0
  lr_init: 5e-5

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 8
  transform_space: true
  transformer:
    factorized_space_time: true
dataset:
  datasets:
  - 'mc_rtt'
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 5

  max_channels: 104
  # max_channels: 98
init_from_id: rtt_5_factor-jdbk361g