# @package _global_
defaults:
  - /model: pretrain_2x
  - /train: pretrain
model:
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none
  # token add not implemented for spacetime

  spike_embed_style: EmbedStrat.token
  neurons_per_token: 2
  hidden_size: 256
  transform_space: true
  transformer:
    n_layers: 10
    factorized_space_time: true

  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
dataset:
  datasets:
  - odoherty_rtt-Indy.* # Note we're just using indy here.
  - mc_rtt
  - mc_maze.*
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1
  # eval_datasets:
  # - mc_rtt
  data_keys:
  - DataKey.spikes
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
  bin_size_ms: 5

  max_channels: 138
  # max_channels: 98
train:
  # DDP doesn't support autoscale as of 2/6/23. Workflow is to manually launch a single GPU run; check batch size, load here.
  autoscale_batch_size: false
  batch_size: 4
load_from_id: rtt_maze_5_factor_2_big_multi-cjo69yg7
