# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat

dataset:
  datasets:
  - odoherty_rtt-Indy.*
  exclude_datasets:
  # Consistent with `arch` experiments
  - odoherty_rtt-Indy-20160407_02 # ~816 trials
  - odoherty_rtt-Indy-20160627_01 # ~3.3K trials (original)
  - odoherty_rtt-Indy-20161005_06 # 373
  - odoherty_rtt-Indy-20161026_03 # ~496 trials
  - odoherty_rtt-Indy-20170131_02 #  814 trials
  odoherty_rtt:
    arrays: ['Indy-M1', 'Loco-M1']
    include_sorted: False
model:
  causal: true
  task:
    mask_ratio: 0.5
  neurons_per_token: 32
train:
  patience: 250