# @package _global_

defaults:
  - /model: pretrain_2x # equivalent to flat_enc_dec without flattening
  - /dataset: base
  - _default_time
model:
  subject_embed_strategy: EmbedStrat.token
dataset:
  max_arrays: 1
  max_channels: 96