# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  causal: True

  task:
    task_weights: [1.0, 2000.0]
    behavior_lag: 0
    decode_time_pool: "mean"
    decode_normalizer: pitt_obs_zscore.pt

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  neurons_per_token: 16
  max_channels: 288

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - observation_.*

  eval_datasets:
  - observation_P2Lab_session_1926.*

train:
  patience: 2000
  autoscale_batch_size: false
  batch_size: 64 # happen to be using 40G this run, 32 x 4
# init_from_id: reach_80000-qp92sqlc
# init_tag: val_loss
