# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 1
  # task_embed_strategy: EmbedStrat.token
  # subject_embed_strategy: EmbedStrat.token

  causal: False

  dropout: 0.8
  transformer:
    n_layers: 6
    debug_override_dropout_io: true
    # debug_force_nonlearned_position: True
  hidden_size: 128

  task:
    mask_ratio: 0.25
  neurons_per_token: 32

  force_zero_mask: True

  # lr_init: 5e-5
  # lr_ramp_steps: 1000
  # lr_decay_steps: 10000
  # accelerate_new_params: 10.0
  # tune_decay: 0.75 # per Kaiming MAE

  lr_ramp_steps: 3000
  lr_decay_steps: 100000
dataset:
  neurons_per_token: 32
  max_arrays: 2

  max_channels: 288
  datasets:
  # - churchland_maze.*
  # - churchland_misc.*
  # - CRS02bHome.data.*
  # - odoherty_rtt.*
  # - mc_maze.*
  - mc_maze_medium
  # - dyer_co.*
  # - gallego_co.*
  eval_datasets:
  - mc_maze_med
  eval_ratio: 0.2
train:
  autoscale_batch_size: false
  batch_size: 64
# init_from_id: maze_f32_acausal-iv6n83mu
# init_tag: val_loss