# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - /train: pretrain
model:
  session_embed_token_count: 1
  causal: False
  hidden_size: 128
  neurons_per_token: 32
dataset:
  datasets:
  - mc_rtt
  eval_datasets:
  - mc_rtt
  eval_ratio: 0.2
  max_channels: 288
  neurons_per_token: 32
train:
  autoscale_batch_size: False
  batch_size: 64