# @package _global_

defaults:
  - /model: pretrain_2x # equivalent to flat_enc_dec without flattening
  - /dataset: flat
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.5 # for efficiency
  readin_strategy: EmbedStrat.unique_project
  readout_strategy: EmbedStrat.unique_project
  readin_compress: False
  readin_dim: 256
  readout_dim: 256

dataset:
  serve_tokenized: False
  serve_tokenized_flat: False

  max_arrays: 1
  max_channels: 224

  scale_ratio: 1.0
  scale_limit_per_eval_session: 300 # no limit

  datasets:
  - mc_maze.*
  - dyer_co.*
  - gallego_co.*
  - odoherty_rtt-Indy-20160627_01
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01

  odoherty_rtt:
    arrays: ["Indy-M1", "Loco-M1"]
    include_sorted: False
train:
  patience: 250
  autoscale_batch_size: false
  batch_size: 512

notes: "Unsorted, transfer task."