# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /model/task: joint_heldout_decode
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 12
  hidden_size: 384

  task:
    mask_ratio: 0.25
    query_heldout: 45
  neurons_per_token: 32

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  tune_decay: 0.75 # per Kaiming MAE

dataset:
  data_keys:
  - DataKey.spikes
  - DataKey.heldout_spikes
  neurons_per_token: 32
  max_tokens: 8192
  max_length_ms: 2000
  max_arrays: 2

  max_channels: 288
  datasets:
  # - churchland_maze.*
  # - churchland_misc.*
  # - P2Home.data.*
  # - odoherty_rtt.*
  # - mc_maze.*
  - mc_rtt
  # - dyer_co.*
  # - gallego_co.*
  eval_datasets:
  - mc_rtt
  eval_ratio: 0.2
train:
  autoscale_batch_size: false
  batch_size: 64
init_from_id: base_f32_150k_acausal-viexqpg7
init_tag: val_loss
sweep_cfg: 'nlb_tune'
sweep_trials: 16