# @package _global_

# Mirror `scale_decode` - pretrain a stable decoder, while varying the unsup source
# Tag refers to unsup source

defaults:
  - /model: flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
  - /train: single_session_exp1
dataset:
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - observation_CRS02bLab_session_19.* #
  - observation_CRS07Lab_session_15.*
  - observation_CRS07Lab_session_16.*
  eval_datasets:
  - observation_CRS02bLab_session_19.* #
  - observation_CRS07Lab_session_15.*
  - observation_CRS07Lab_session_16.*
model:

  causal: true
  neurons_per_token: 32
  task:
    task_weights: [1.0, 0.1]
    mask_ratio: 0.2
    behavior_lag: 40
    decode_normalizer: pitt_obs_zscore.pt

  accelerate_new_params: 10.0 # We're introducing a whole new readout layer...
  lr_schedule: 'fixed'
# No fragment
inherit_exp: pitt_v2/decode
sweep_cfg: 'simpler_lr_sweep'
sweep_mode: 'grid'