# @package _global_
# TODO think about LR
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: small
  - /dataset: flat
model:
  neurons_per_token: 8

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0

dataset:
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 8
  max_channels: 104

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - odoherty_rtt-Indy-20161005_06
  # - odoherty_rtt-Indy-20161014_04
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1

init_from_id: rtt_indy_flat_shuffle_single-sweep-lr_and_dropout-xecx9bae
init_tag: val_loss