# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    # - accel_tune
  - /model/task:
    - bhvr_decode_flat
  - /train: finetune
  - /dataset: flat
model:
  neurons_per_token: 8

  lr_init: 5e-5
  lr_ramp_steps: 1000
  lr_decay_steps: 10000
  accelerate_new_params: 10.0
  task:
    # mask_ratio: 0.8 # assuming high mask ratio was what prevented overfitting in pretraining, try it again here
    decode_separate: True
    behavior_lag: 120
dataset:
  max_length_ms: 2000 # fit
  max_arrays: 1

  neurons_per_token: 8
  max_channels: 104

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - odoherty_rtt-Indy.*
  # - odoherty_rtt-Indy-20161014_04
  eval_datasets:
  - odoherty_rtt-Indy-20161005_06
  odoherty_rtt:
    arrays:
    - Indy-M1
    - Loco-M1

init_from_id: rtt_indy_flat_shuffle-sweep-lr_and_dropout-j0twjjbo # 0.3204
init_tag: val_loss

# # ! New, testing regularization strategies
train:
  accumulate_batches: 4 # simulate 4x gpu
sweep_cfg: reg_tight
sweep_trials: 8