# @package _global_
# For use in NLB
defaults:
  - /model: flat_enc_dec
  - /train: pretrain
  - /dataset: flat
model:
  session_embed_token_count: 8
  task_embed_strategy: EmbedStrat.token
  subject_embed_strategy: EmbedStrat.token

  causal: False

  transformer:
    n_layers: 12
    pre_norm: true
  hidden_size: 384

  task:
    mask_ratio: 0.1
  neurons_per_token: 32

dataset:
  neurons_per_token: 32
  max_tokens: 8192
  max_channels: 288
  datasets:
  - churchland_maze.*
  - churchland_misc.*
  # - CRS02bHome.data.*
  - odoherty_rtt.*
  - mc_maze$
  - dyer_co.*
  - gallego_co.*
  eval_datasets:
  - mc_maze$
train:
  accumulate_batches: 1 # assumed to be running on 40G A100, base size 128
  # autoscale_batch_size: false
  # batch_size: 32
notes: "Not run, cf `norm/prenorm` which is the same config as here"